add interceptor
holoviz/lumen pull request #642
Opened 2024-08-08 00:15 UTC by ahuang11

Was hoping that this would capture instructor's inputs, but I think I have to go a level deeper.

```python
import openai
llm = openai.AsyncClient()
import instructor
from pydantic import BaseModel
client = instructor.from_openai(llm)

class Feelings(BaseModel):

    feelings: list[str]

interceptor = OpenAIInterceptor()
interceptor.patch_create(client)

response = await client.chat.completions.create(
    messages=[
        {"role": "system", "content": "Be a helpful assistant."},
        {"role": "user", "content": "How are you?"},
    ],
    model="gpt-4o-mini",
    stream=True,
    response_model=instructor.Partial[Feelings]
)
async for chunk in response:
    print(chunk)
interceptor.get_all_session_message_groups()
```

2024-08-08 17:29 UTC, ahuang11 commented
<details>
  <summary>Example Lumen output</summary>

  ```python
  [{'batch_id': 1,
    'messages': [{'role': 'system',
        'content': "Select the most relevant agent for the user's query.\n\nEach agent can request other agents to fill in the blanks, so pick the agent that can best answer the entire query.\n\nHere's the choice of agents and their uses:\n```\n\n- `SourceAgent`: The SourceAgent allows a user to provide an input source. Should only be used if the user explicitly requests adding a source or no source is in memory.\n\n- `TableAgent`: Displays a single table / dataset. Does not discuss.\n\n- `SQLAgent`: Responsible for generating and modifying SQL queries to answer user queries about the data, such querying subsets of the data, aggregating the data and calculating results.\n\n- `PipelineAgent`: Generates a data pipeline by applying SQL to the data. If the user asks to calculate, aggregate, select or perform some other operation on the data this is your best best.\n\n- `hvPlotAgent`: Generates a plot of the data given a user prompt. If the user asks to plot, visualize or render the data this is your best best.\n\n- `ChatAgent`: Chats and provides info about high level data related topics, e.g. what datasets are available, the columns of the data or statistics about the data, and continuing the conversation. Is capable of providing suggestions to get started or comment on interesting tidbits. If data is available, it can also talk about the data itself.\n\n- `AnalysisAgent`: Available analyses include: - `YdataProfiling`: Provides high level data profiling. Select this agent to perform one of these analyses.\n\n```"},
    {'role': 'user', 'content': 'Show table'}],
    'kwargs': {'model': 'gpt-4o-mini',
    'temperature': 0.2,
    'tools': [{'type': 'function',
        'function': {'name': 'RelevantAgent',
        'description': 'Correctly extracted `RelevantAgent` with all the required parameters with correct types',
        'parameters': {'properties': {'chain_of_thought': {'description': 'Explain in your own words, what the user wants.',
            'title': 'Chain Of Thought',
            'type': 'string'},
            'agent': {'description': 'The most relevant agent to use.',
            'enum': ['SourceAgent',
            'TableAgent',
            'SQLAgent',
            'PipelineAgent',
            'hvPlotAgent',
            'ChatAgent',
            'AnalysisAgent'],
            'title': 'Agent',
            'type': 'string'}},
        'required': ['agent', 'chain_of_thought'],
        'type': 'object'}}}],
    'tool_choice': {'type': 'function', 'function': {'name': 'RelevantAgent'}}},
    'response': '{"chain_of_thought": "The user is requesting to see a table, which indicates they want to display a dataset. The most suitable agent for this task is the TableAgent, as it is specifically designed to display a single table or dataset without further discussion.", "agent": "TableAgent"}'},
    {'batch_id': 2,
    'messages': [{'role': 'system',
        'content': 'Based on the latest user\'s query, decide whether the current table and data contains the the required data. If the user is referencing "this data" or "that" they probably are referring to the current data. Pay particular attention to whether the data actually contains the columns required to answer the query, e.g. if they are asking for a location but there are no location related column the data is invalid.\n\n### Current Table:\n```\nwindturbines.parquet\n```\n\n### Current SQL:\n```\nNone\n```\n\n### Current Data `{column: stat}`:\n```\n{\'case_id\': {\'type\': \'integer\', \'min\': 3000001, \'max\': 3125948}, \'faa_ors\': {\'type\': \'string\', \'enum\': [\'39-003863\', \'19-020351\', \'19-020377\', \'19-020448\', \'19-058716\', \'...\']}, \'faa_asn\': {\'type\': \'string\', \'enum\': [\'2016-WTE-5934-OE\', \'2013-WTE-5497-OE\', \'2018-WTE-9908-OE\', \'2018-WTE-9870-OE\', \'2018-WTE-9867-OE\', \'...\']}, \'usgs_pr_id\': {\'type\': \'number\', \'min\': 1.0, \'max\': 49135.0}, \'eia_id\': {\'type\': \'number\', \'min\': 90.0, \'max\': 65525.0}, \'t_state\': {\'type\': \'string\', \'enum\': [\'OH\', \'IN\', \'CO\', \'OR\', \'AK\', \'...\']}, \'t_county\': {\'type\': \'string\', \'enum\': [\'Kern County\', \'Poweshiek County\', \'Barnstable County\', \'Laramie County\', \'Blair County\', \'...\']}, \'t_fips\': {\'type\': \'integer\', \'min\': 2013, \'max\': 72133}, \'p_name\': {\'type\': \'string\', \'enum\': [\'Agriwind\', \'Ainsworth Wind Project (NPPD)\', \'Alta III\', \'Amazon Wind Farm (Fowler Ridge)\', \'Anacacho\', \'...\']}, \'p_year\': {\'type\': \'number\', \'min\': 1981.0, \'max\': 2022.0}, \'p_tnum\': {\'type\': \'integer\', \'min\': 1, \'max\': 731}, \'p_cap\': {\'type\': \'number\', \'min\': 0.05, \'max\': 1055.6}, \'t_manu\': {\'type\': \'string\', \'enum\': [\'Siemens\', \'Kenersys\', \'Aeronautica\', \'AAER\', \'Vensys\', \'...\']}, \'t_model\': {\'type\': \'string\', \'enum\': [\'SWT-2.3-108\', \'ECO 86\', \'V82-1.65\', \'FL1500\', \'GE2.85-103\', \'...\']}, \'t_cap\': {\'type\': \'number\', \'min\': 50.0, \'max\': 6000.0}, \'t_hh\': {\'type\': \'number\', \'min\': 19.0, \'max\': 137.0}, \'t_rd\': {\'type\': \'number\', \'min\': 13.4, \'max\': 162.0}, \'t_rsa\': {\'type\': \'number\', \'min\': 141.03, \'max\': 20611.99}, \'t_ttlh\': {\'type\': \'number\', \'min\': 30.4, \'max\': 205.4}, \'retrofit\': {\'type\': \'integer\', \'min\': 0, \'max\': 1}, \'retrofit_year\': {\'type\': \'number\', \'min\': 2015.0, \'max\': 2021.0}, \'t_conf_atr\': {\'type\': \'integer\', \'min\': 1, \'max\': 3}, \'t_conf_loc\': {\'type\': \'integer\', \'min\': 1, \'max\': 3}, \'t_img_date\': {\'type\': \'string\', \'format\': \'datetime\', \'min\': \'1993-06-14 00:00:00\', \'max\': \'2022-09-06 00:00:00\'}, \'t_img_srce\': {\'type\': \'string\', \'enum\': [\'NAIP\', \'Google Earth\', \'Bing Maps Aerial\', \'Digital Globe\']}, \'xlong\': {\'type\': \'number\', \'min\': -171.713074, \'max\': 144.722656}, \'ylat\': {\'type\': \'number\', \'min\': 13.389381, \'max\': 66.839905}, \'easting\': {\'type\': \'number\', \'min\': -19115011.960227706, \'max\': 16110452.372170098}, \'northing\': {\'type\': \'number\', \'min\': 1504253.4146257618, \'max\': 10110596.985745305}}\n```\n\n\nIf the user requests one of the current analyses, the data is assumed to be valid.\n\n### Current Analyses:\n\n- <class \'bokeh_app_5a551904cf0e428da1abcc36b35f26d4.YdataProfiling\'>'},
    {'role': 'assistant',
        'content': "source:\n  initializers:\n  - INSTALL httpfs;\n  - LOAD httpfs;\n  tables:\n  - windturbines.parquet\n  type: duckdb\n  uri: ':memory:'\ntable: windturbines.parquet\n"},
    {'role': 'user', 'content': 'Tell me about this table'}],
    'kwargs': {'model': 'gpt-4o-mini',
    'temperature': 0.2,
    'tools': [{'type': 'function',
        'function': {'name': 'Validity',
        'description': 'Correctly extracted `Validity` with all the required parameters with correct types',
        'parameters': {'properties': {'correct_assessment': {'description': "\n        Thoughts on whether the current table meets the requirement\n        to answer the user's query, i.e. table contains all necessary columns,\n        unless user explicitly asks for a refresh.\n        ",
            'title': 'Correct Assessment',
            'type': 'string'},
            'is_invalid': {'anyOf': [{'enum': ['table', 'sql'], 'type': 'string'},
            {'type': 'null'}],
            'description': 'Whether the `table` or `sql` is invalid or no longer relevant depending on correct assessment. None if valid.',
            'title': 'Is Invalid'}},
        'required': ['correct_assessment', 'is_invalid'],
        'type': 'object'}}}],
    'tool_choice': {'type': 'function', 'function': {'name': 'Validity'}}},
    'response': '{"correct_assessment": "The table contains data related to wind turbines, including various attributes such as case ID, FAA identifiers, state, county, project name, year, capacity, manuf [...]

2024-08-13 09:50 UTC, philippjfr reviewed
Looks nice, can you write out or generate some diagrams for the SQL schemas?

2024-09-18 21:19 UTC, ahuang11 commented
Here's a diagram:

<img width="732" alt="image" src="https://github.com/user-attachments/assets/8d5575b5-e27c-4ee8-89b3-ace172d8528e">

- session_ids are per session (e.g. each time opening up the app and seeing the ChatInterface)

- batches are a group of messages, e.g.
  - prompt may be: Show me olympics_medals table
    - Batch 1: RelevantAgent needs to choose the agent
      - {system_message_for_relevant_agent, past_messages, user_prompt}
    - Batch 2: TableAgent needs to select the table
      - {system_message_for_**table**_agent, past_messages, user_prompt}

- messages are system/assistant/user messages

Here are the messages output
<img width="868" alt="image" src="https://github.com/user-attachments/assets/722d429f-3d64-4683-94af-05d19b40fe55">

Here are the responses output
<img width="657" alt="image" src="https://github.com/user-attachments/assets/5ab86d27-8e38-43e0-8140-c40cf0c6a220">


I don't really remember why I store message_kwargs; maybe just for archival reasons
<img width="666" alt="image" src="https://github.com/user-attachments/assets/dbcd8194-62dd-4206-abda-a66a3a3b0dba">

2024-09-24 17:07 UTC, ahuang11 commented
Not planning to support MistralAI & AnthropicAI in this PR

2024-10-10 23:55 UTC, ahuang11 commented
Updated the tables.

<img width="411" alt="image" src="https://github.com/user-attachments/assets/8784bfbc-ce6f-40ef-99b1-c36f792dff3b">

Each invocation is a `llm.invoke()` call.

In `get_session` I postprocess it a bit to gather `input_id` and `prompt` from messages (parsing for user message)

<img width="1244" alt="image" src="https://github.com/user-attachments/assets/f1f76728-8500-45b4-b92f-07cb06718118">

2024-10-16 10:27 UTC, philippjfr approved these changes

2024-10-16 10:29 UTC, philippjfr commented on lumen/ai/llm.py
> +    interceptor_path = param.String(default=None)
I would simply allow passing the interceptor instance, that way it's actually composable.

2024-10-16 10:30 UTC, philippjfr requested changes
Looks good, but as noted above I think we want a composable approach instead of hardcoding the Interceptor type.

2024-10-21 15:06 UTC, merged