Improve sql agent
holoviz/lumen pull request #795
Opened 2024-11-27 21:40 UTC by ahuang11

This was driving me nuts and took me a while to debug:

<img width="683" alt="image" src="https://github.com/user-attachments/assets/d80b68f7-7952-4818-86d3-07355cc1eca1">

The shown SQL was valid, but internally, with `SQLLimit` transform, it was wrapping another layer of `SELECT *...` incorrectly, but the UI was not showing the final query...

1. Fixed with a regex to more robustly search for `SELECT ... FROM`; previously, it was doing `'select ' in`, but wasn't able to pick up `'select\n'`
2. added a jinja2 `examples` block so I can add example outputs, and users can also drop in examples, separately from instructions/context
3. changed the limit from 3 to 1000 because it was caching it, and it wasn't picking up enough enums to be useful for future cached queries
4. gave an example for expr_slug; sometimes it gave slugs with spaces "Top ..." which isn't a slug imo.
5. more checklist guidance for sqlagent

2024-11-27 21:50 UTC, amaloney requested changes
you need to fix the typo, but otherwise looks good

2024-11-27 21:50 UTC, amaloney commented on lumen/ai/prompts/SQLAgent/main.jinja2
> +- Use Common Table Expressions (CTEs) and subqueries to break down complex queries into manageable parts.
nice, CTEs are awesome

2024-11-27 21:50 UTC, amaloney commented on lumen/ai/prompts/SQLAgent/main.jinja2
> +LIMI5 1;
typo?

2024-11-27 22:00 UTC, ahuang11 commented on lumen/ai/prompts/SQLAgent/main.jinja2
> +LIMI5 1;
```suggestion
LIMIT 1;
```

2024-11-27 22:00 UTC, ahuang11 commented on lumen/ai/prompts/SQLAgent/main.jinja2
> +LIMI5 1;
Nice catch!

2024-11-27 23:39 UTC, amaloney approved these changes

2024-12-02 08:59 UTC, philippjfr approved these changes

2024-12-02 08:59 UTC, merged

2024-12-03 18:08 UTC, ahuang11 commented on lumen/ai/ui.py
> +                name='ProvidedSource00000'
Strange that it's shown in this PR, but
> The LLM sometimes dropped the source, but by naming the Provided DuckDBSource like the other randomly named DuckDBSources, it seems to properly keep the name.



https://github.com/holoviz/lumen/pull/796