Custom data source
holoviz/lumen pull request #866
Opened 2024-12-13 23:30 UTC by amaloney

2024-12-16 13:32 UTC, philippjfr commented on doc/how_to/ai_config/custom_data_source.md
> +Ensure your API key is in the environment of the terminal you run your commands in.
I know this is early but just as a heads up, each how-to will be pretty standalone. You should assume that a user has configured the LLM already, either by reading the getting started or the how-to on configuring the LLM.

2024-12-16 22:25 UTC, amaloney commented
@ahuang11 rebased and updated with suggestions and an app example.

2024-12-17 13:14 UTC, philippjfr requested changes
Thanks, a good start! I'd like to add a section about configuring a custom data source, e.g. an example like this:

```python
from lumen.sources.snowflake import SnowflakeSource

import lumen.ai as lmai

source = SnowflakeSource(
    account='...',
    authenticator='externalbrowser',
    database='...',
    user='...',
)

lmai.ExplorerUI(source).servable()
```

2024-12-17 19:20 UTC, ahuang11 commented
I would also add if the filename has an unexpected extension, like `.parq` I don't think duckdb is automatically able to infer it, so you may need `read_parquet("file.parq")`

2024-12-18 20:29 UTC, amaloney commented
@ahuang11 are you suggesting that a user will need to do something like the following?

```python
import lumen.ai as lmai
import pandas as pd

lmai.ExploreUI(
    data=[pd.read_parquet("path/to/weird/extension.parket")],
    llm=lmai.llm.Llama(),
    agents=[lmai.agents.SQLAgent],
)
```

2024-12-18 20:37 UTC, ahuang11 commented
Nah, to clarify, duckdb supports this https://duckdb.org/docs/data/parquet/overview.html natively.

So we need to just pass the directive:
`read_parquet("file.parq")`

2024-12-18 22:33 UTC, ahuang11 commented on doc/how_to/ai_config/custom_data_source.md
> +### DuckDb
Following their branding:
```suggestion
### DuckDB
```

Also, I think it'd be nice to mention/show it supports more than just parq, like csv.

2024-12-18 22:34 UTC, ahuang11 commented on doc/how_to/ai_config/custom_data_source.md
> +
Maybe you can also mention directly uploading in the UI

2024-12-19 18:16 UTC, ahuang11 approved these changes

2024-12-30 12:19 UTC, philippjfr commented on doc/how_to/ai_config/custom_data_source.md
> +
I'll drop this, we don't support `catalog` like this and I think we're de-emphasizing Intake going forward.

```suggestion
```

2024-12-30 12:20 UTC, philippjfr approved these changes
Looks great, thank you!

2025-01-02 17:10 UTC, merged